version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-yolofarm
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env  # 📌 Đọc biến môi trường từ file .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: mongo-yolofarm
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env  # 📌 Đọc biến môi trường từ file .env
    volumes:
      - mongo_data:/data/db             
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}

volumes:
  mongo_data: