version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-yolofarm
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/yolofarm
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: mongo-yolofarm
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: yolofarm
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

